// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsy8rZO8TNZTONvt6fyIu2n_H_M7MMFco',
    appId: '1:248554494436:web:7c796d5d73a27963074ff1',
    messagingSenderId: '248554494436',
    projectId: 'flutter-job-seeker',
    authDomain: 'flutter-job-seeker.firebaseapp.com',
    databaseURL: 'https://flutter-job-seeker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-job-seeker.appspot.com',
    measurementId: 'G-N22S7D2W6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyGdeER5qEX_Cat5c5hlT99bN1BKW50Po',
    appId: '1:248554494436:android:f731649210725b5b074ff1',
    messagingSenderId: '248554494436',
    projectId: 'flutter-job-seeker',
    databaseURL: 'https://flutter-job-seeker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-job-seeker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCszS2ji1yjttvYBmtxK08eDsx7Q_IF1vs',
    appId: '1:248554494436:ios:d759085b4cfbc7bf074ff1',
    messagingSenderId: '248554494436',
    projectId: 'flutter-job-seeker',
    databaseURL: 'https://flutter-job-seeker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-job-seeker.appspot.com',
    androidClientId: '248554494436-39cqirh2f9i35jge6ljjp1kpojpmgk9o.apps.googleusercontent.com',
    iosClientId: '248554494436-noc4jvhmfbi73b44dt9jo2ka9kesadcu.apps.googleusercontent.com',
    iosBundleId: 'asia.nfq.jobSeeker',
  );
}
